### ISSUE TITLE
Writing in the textfield causes text to appear in center

### ISSUE THREAD

**Issue by poovamraj** [SandeepAggarwal/SACodedTextField#1]
Hello,
Good work with the library.
I am having a small issue where when writing in the text field causes string to appear in the center of the text field (not the intended) place. Please look into the screenshot for a better understanding

![image 2017-12-08 12_32_10 54 pm](https://user-images.githubusercontent.com/15910425/33754832-2953fcfc-dc14-11e7-846d-2c16b3403007.PNG)

**Comment by SandeepAggarwal** [comment]
What is the `maxCodeLength` set?  What is the width of the text field ? Did you use `- (CGFloat) minWidthTextField` to get the minimum width?

**Comment by poovamraj** [comment]
No worries bro I wrote a view on my own. Anyway great library. I guess the fault could be on my side.
